<?php
/**
 * @var $block \RightpointAssignment\SalesOrderNewSection\Block\Adminhtml\Order\View
 */
?>
<div class="admin__page-section-item order-custom-information">
    <div class="admin__page-section-item-title">
        <span class="title">Additional Details</span>
    </div>
    <hr>
    <div class="admin__page-section-item-content">
        <div class="order-custom-information-title"><?=$block->getOrderCustom() ?></div>
    </div>
</div>
